acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('delete2/', views.delete2, name='delete2'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('vote/', include('vote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vote/urls.py
from django.urls import path
from . import views
app_name = "vote"
urlpatterns = [
    path('index/', views.index, name='index'),
    path('detail/<tpk>', views.detail, name='detail'),
    path('vote/<tpk>', views.vote, name='vote'),
    path('create/', views.create, name='create'),
]

vote/models.py
from django.db import models
from acc.models import User
# Create your models here.
class Topic(models.Model):
    subject = models.CharField(max_length=100)
    maker = models.ForeignKey(User, on_delete=models.CASCADE, related_name="maker")
    content = models.TextField()
    pubdate = models.DateTimeField()
    voter = models.ManyToManyField(User, blank=True, related_name="voter")

    def __str__(self):
        return self.subject

class Choice(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    num = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.topic}_{self.name}"

vote/views.py
from django.shortcuts import render, redirect
from .models import Topic, Choice
from django.utils import timezone
# Create your views here.
def index(req):
    t = Topic.objects.all()
    context = {
        "tset" : t
    }
    return render(req, 'vote/index.html', context)

def detail(req, tpk):
    t = Topic.objects.get(id=tpk)
    c = t.choice_set.all()
    context = {
        "t":t,
        "cset":c
    }
    return render(req, 'vote/detail.html', context)

def vote(req,tpk):
    t = Topic.objects.get(id=tpk)
    if not req.user in t.voter.all():
        t.voter.add(req.user)
        cpk = req.POST.get("cho")
        c = Choice.objects.get(id=cpk)
        c.num += 1
        c.save()
    else:
        pass # 메세지!
    return redirect("vote:detail", tpk)

def create(req):
    if req.method == "POST":
        s = req.POST.get("sub")
        c = req.POST.get("con")
        m = req.POST.getlist("chname")   # 동일한 값으로 여러개를 받을 경우!
        if len(m) > 2:
            t = Topic(subject=s, maker=req.user, content=c, pubdate=timezone.now())
            t.save()

            for i in m:
                Choice(topic=t, name=i).save()
            return redirect('vote:index')
    return render(req, 'vote/create.html')

templates/vote/create.html
{% extends 'base.html' %}

{% block con %}

<form method="post">
    {% csrf_token %}
    <input type="text" size="30" name="sub" placeholder="투표 주제"><br><br>
    <textarea cols="40" rows="5" name="con" placeholder="투표 설명"></textarea><br><br>
    <div id="here"></div>

    <hr>
    
    <button type="button" onclick="make_choice()">선택지 생성</button>
    <button>투표 생성</button>
</form>

    <script>
        function make_choice(){
            d = document.getElementById("here");
            n = document.createElement("div");
            n.innerHTML = "보기 <input type='text' name='chname'> <br>";
            d.appendChild(n);
        }
    </script>

{% endblock %}

templates/vote/detail.html
{% extends 'base.html' %}

{% block con %}

    {% load mathfilters %}
    <h1>VOTE DETAIL PAGE</h1>
    <h2><b>{{ t.subject }}</b></h2>

    <img src="{{ t.maker.getpic }}" width="300px">
    <br> <b>{{ t.maker }}</b> <br> {{ t.pubdate }} <br>
    <br>
    <textarea cols="70" rows="3" disabled>{{ t.content }}</textarea><br><br>

    {% if user in t.voter.all %}
        {% for i in cset %}
            <b>{{ i.name }}</b>투표율 : {{ i.num|div:t.voter.count|mul:100 }} %<br><br>
        {% endfor %}
    {% else %}
        <form method="post" action="{% url 'vote:vote' t.id %}">
            {% csrf_token %}
            {% for i in cset %}
                <input type="radio" name="cho" value="{{ i.id }}" >{{ i.name }}<br>
            {% endfor %}
            <button>투표</button>
        </form>
    {% endif %}
    <a href="{% url 'vote:index' %}"><button>홈</button></a>
{% endblock %}

templates/vote/index.html
{% extends 'base.html' %}

{% block con %}
<h1>VOTE PAGE</h1>
<h2><b>투표소</b></h2>

<a href="{% url 'vote:create' %}"><button>투표 생성</button></a>

<ul>
    {% for i in tset %}
    <li><a href="{% url 'vote:detail' i.id %}">{{ i.subject }} {% if user in i.voter.all %} 👌 {% endif %}</a></li>
    {% endfor %}
</ul>
{% endblock %}