acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('delete2/', views.delete2, name='delete2'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('vote/', include('vote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acc/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    pic = models.ImageField(upload_to="user/%y/%m")
    comment = models.TextField()
    age = models.IntegerField(default=1)

    def getpic(self):
        if self.pic:
            return self.pic.url
        else:
            return "/media/user/noimage.png"

acc/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.hashers import check_password
from .models import User
from django.contrib import messages
# Create your views here.
def index(req):
    return render(req, 'acc/index.html')

def login_user(req):
    if req.method == "POST":
        un = req.POST.get("uname")
        up = req.POST.get("upass")
        u = authenticate(username=un, password=up)
        if u:
            login(req, u)
            return redirect("acc:index")
        else:
            messages.error(req, "로그인 실패")
    return render(req, 'acc/login.html')

def logout_user(req):
    logout(req)
    return redirect("acc:index")

def signup(req):
    if req.method == "POST":
        un = req.POST.get("uname")
        up = req.POST.get("upass")
        ua = req.POST.get("uage")
        pi = req.FILES.get("upic")
        uc = req.POST.get("ucom")
        try:
            User.objects.create_user(username=un, password=up, age=ua, pic=pi, comment=uc)
            return redirect('acc:login')
        except:
            messages.error(req, "사용자 이름이 중복됩니다")     
    return render(req, 'acc/signup.html')

def profile(req):
    return render(req, 'acc/profile.html')

def update(req):
    if req.method == "POST":
        u = req.user
        up = req.POST.get("upass")
        ue = req.POST.get("email")
        ua = req.POST.get("uage")
        pi = req.FILES.get("upic")
        uc = req.POST.get("ucom")
        if up:
            u.set_password(up)
        if pi:
            u.pic.delete()
            u.pic = pi
        u.email = ue
        u.age = ua
        u.comment = uc
        u.save()
        login(req, u)
        return redirect('acc:profile')
    return render(req, 'acc/update.html')

def delete(req):
    if req.method == "POST":
        up = req.POST.get("upass")
        if check_password(up, req.user.password):
            req.user.delete()
            return redirect('acc:index')
        else:
            messages.error(req, "비밀번호가 일치하지 않습니다.")
            return redirect('acc:profile')
    return render(req, 'acc/delete.html')

def delete2(req):
    pwck = req.POST.get("pwck")
    print(pwck)
    if check_password(pwck, req.user.password):
        req.user.pic.delete()
        req.user.delete()
        return redirect('acc:index')
    else:
        messages.error(req, "비밀번호가 일치하지 않습니다.")
        return redirect('acc:profile')

templates/acc/delete.html
{% extends 'base.html' %}

{% block con %}
<h1>계정 삭제 페이지</h1>
<form method="post">
    {% csrf_token %}
    PASSWORD 확인 <input type="password" name="upass"><br><br>
    <button>삭제</button>
</form>
{% endblock %}

templates/acc/index.html
{% extends 'base.html' %}

{% block con %}
<h1>WELCOME {{ user }}!! 🎉</h1><br><br>
{% endblock %}

templates/acc/login.html
{% extends 'base.html' %}

{% block con %}
    <h1>LOGIN PAGE</h1>
    
    <form method="post">
        {% csrf_token %}
        <input type="text" name="uname"><br><br>
        <input type="password" name="upass"><br><br>
        <button>로그인</button>
    </form>
{% endblock %}

templates/acc/profile.html
{% extends 'base.html' %}

{% block con %}
    <h1> {{ user }}'s PROFILE </h1>
    <img src="{{ user.getpic }}" width="350px">
    <table>
        <tr>
            <th>USERNAME</th>
            <td><input type="text" value="{{ user.username }}" name="uname" disabled></td>
        </tr>
        <tr>
            <th>AGE</th>
            <td><input type="number" value="{{ user.age }}" name="uage" disabled></td>
        </tr>
        <tr>
            <th>EMAIL</th>
            <td><input type="text" value="{{ user.email }}" name="umail" disabled></td>
        </tr>
        <tr>
            <th>COMMENT</th>
            <td><textarea cols="50" rows="5" name="ucom" disalbed>{{ user.comment }}</textarea></td>
        </tr>
    </table>

    <a href="{% url 'acc:update' %}"><button>정보 수정</button></a>
    <a href="{% url 'acc:delete' %}"><button type="button">계정 삭제</button></a>

    <button type="button" id="delbutton" onclick="make_del()">계정삭제js</button>

    <form method="POST" id="here" action="{% url 'acc:delete2' %}">
        {% csrf_token %}
    </form>

    <script>
        function make_del(){
            d = document.getElementById("here");
            bu = document.getElementById("delbutton");
            bu.setAttribute("disabled", "true");
            fo = document.createElement("div");
            fo.innerHTML = "<br><h4><b>삭제하시려면 패스워드를 입력해주세요</b></h4><hr><b>PASSWORD CHECK</b> <input type='password' name='pwck'> <button>삭제</button><br><hr>";
            d.appendChild(fo);
        }
    </script>

{% endblock %}

templates/acc/signup.html
{% extends 'base.html' %}

{% block con %}

    <h1>SIGNUP PAGE</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                <th>USERNAME</th>
                <td><input type="text" name="uname"></td>
            </tr>
            <tr>
                <th>PASSWORD</th>
                <td><input type="password" name="upass"></td>
            </tr>
            <tr>
                <th>AGE</th>
                <td><input type="number" name="uage"></td>
            </tr>
            <tr>
                <th>PIC</th>
                <td><input type="file" name="upic"></td>
            </tr>
            <tr>
                <th>COMMENT</th>
                <td><textarea cols="50" rows="5" name="ucom"></textarea></td>
            </tr>
        </table>
        <button>가입</button>
    </form>
{% endblock %}

templates/acc/update.html
{% extends 'base.html' %}

{% block con %}

    <h1>{{ user }}'s' UPDATE PAGE</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                <th>USERNAME</th>
                <td><input type="text" value="{{ user.username }}" name="uname" disabled></td>
            </tr>
            <tr>
                <th>PASSWORD</th>
                <td><input type="password" name="upass"></td>
            </tr>
            <tr>
                <th>EMAIL</th>
                <td><input type="text" name="email" value="{{ user.email }}"></td>
            </tr>
            <tr>
                <th>AGE</th>
                <td><input type="number" value="{{ user.age }}" name="uage"></td>
            </tr>
            <tr>
                <th>PIC</th>
                <td><input type="file" name="upic"></td>
            </tr>
            <tr>
                <th>COMMENT</th>
                <td><textarea cols="50" rows="5" name="ucom">{{ user.comment }}</textarea></td>
            </tr>
        </table>
        <button>수정 완료</button>
    </form>
{% endblock %}