acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('delete2/', views.delete2, name='delete2'),
]

board/urls.py
from django.urls import path
from . import views
app_name = "board"
urlpatterns = [
    path('index/', views.index, name='index'),
    path('detail/<bpk>', views.detail, name='detail'),
    path('delete/<bpk>', views.delete, name='delete'),
    path('create/', views.create, name='create'),
    path('update/<bpk>', views.update, name='update'),
    path('likey/<bpk>', views.likey, name='likey'),
    path('unlikey/<bpk>', views.unlikey, name='unlikey'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('vote/', include('vote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trans/urls.py
from django.urls import path
from . import views
app_name = "trans"
urlpatterns = [
    path('index/', views.index, name='index'),
]

vote/urls.py
from django.urls import path
from . import views
app_name = "vote"
urlpatterns = [
    path('index/', views.index, name='index'),
    path('detail/<tpk>', views.detail, name='detail'),
    path('vote/<tpk>', views.vote, name='vote'),
    path('create/', views.create, name='create'),
]

templates/base.html
{% if user.is_authenticated %}
    <div>
        <a href="{% url 'acc:index' %}" class="menu">HOME</a>
        <a href="{% url 'board:index' %}" class="menu">BOARD</a>
        <a href="{% url 'acc:profile' %}" class="menu">PROFILE</a>
        <a href="{% url 'trans:index' %}" class="menu">TRANS</a>
        <a href="{% url 'vote:index' %}" class="menu">VOTE</a>
        <a href="{% url 'acc:logout' %}" class="menu">LOGOUT</a> 
        접속중인 계정 : {{ user }}
    </div>
{% else %}
    <div>
        <a href="{% url 'acc:index' %}" class="menu">HOME</a>
        <a href="{% url 'acc:login' %}" class="menu">LOGIN</a>
        <a href="{% url 'acc:signup' %}" class="menu">SIGNUP</a>
    </div>
{% endif %}

<hr>

{% for i in messages %}
    <div class="{{i.tags}}">
        <b>{{ i.tags|upper }}</b> {{ i.message }}
    </div>
{% endfor %}

{% block con %}
{% endblock %}

<style>
    .info{
        background-color:azure
    }
    .error{
        background-color:red
    }
    .success{
        background-color:rgb(97, 33, 175)
    }
    .warning{
        background-color:rgb(123, 152, 4)
    }

    .menu{
        text-decoration: none;
        font-size: 25px;
        color: black;
        font-weight: Bold;
        margin-right: 10px;
    }
    .menu:hover{
        color: blue;
    }
</style>