acc/urls.py
from django.urls import path
from . import views

app_name = "acc"

urlpatterns = [
    path('index/', views.index, name="index"),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('update/', views.update, name='update'),
    path('delete/', views.delete, name='delete'),
    path('delete2/', views.delete2, name='delete2'),
]

board/urls.py
from django.urls import path
from . import views
app_name = "board"
urlpatterns = [
    path('index/', views.index, name='index'),
    path('detail/<bpk>', views.detail, name='detail'),
    path('delete/<bpk>', views.delete, name='delete'),
    path('create/', views.create, name='create'),
    path('update/<bpk>', views.update, name='update'),
    path('likey/<bpk>', views.likey, name='likey'),
    path('unlikey/<bpk>', views.unlikey, name='unlikey'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('acc/', include('acc.urls')),
    path('board/', include('board.urls')),
    path('trans/', include('trans.urls')),
    path('vote/', include('vote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
from django.db import models
from acc.models import User
# Create your models here.
class Board(models.Model):
    subject = models.CharField(max_length=100)
    writer = models.ForeignKey(User, on_delete=models.CASCADE, related_name='writer')
    content = models.TextField()
    likey = models.ManyToManyField(User, blank=True, related_name='likey')
    pubdate = models.DateTimeField()

    def __str__(self):
        return self.subject

    def summary(self):
        if len(self.content) > 50:
            return f"{self.content[:50]} ..."
        return self.content

board/views.py
from django.shortcuts import render, redirect
from .models import Board
from django.utils import timezone
from django.core.paginator import Paginator

# Create your views here.

def index(req):
    pg = req.GET.get("page", 1)   # get 인자에 page가 없으면 1, 있으면 page값을 전송하겠다! - get 인자는 url로 정보를 전송하겠다!
    cate = req.GET.get("cate", "")
    kw = req.GET.get("kw","")

    if kw:
        if cate == "sub":
            b = Board.objects.filter(subject__startswith=kw)
        elif cate == "wri":
            try:
                from acc.models import User
                u = User.objects.get(username=kw)
                b = Board.objects.filter(writer=u)
            except:
                b = Board.objects.none()
        elif cate == "con":
            b = Board.objects.filter(content__contains=kw)
        else:
            b = Board.objects.all()
    else:
        b = Board.objects.all()

    # Paginator(A,B)
    # A:  레코드들 / B : 단위
    pag = Paginator(b,10)
    obj = pag.get_page(pg)  # n 페이지를 보고 싶으면 숫자를 넣는다!
    context = {
        "bset": obj,
        "cate" : cate,
        "kw" : kw
    }
    return render(req, 'board/index.html', context)

def detail(req, bpk):
    b = Board.objects.get(id=bpk)
    context = {
        "b": b
    }
    return render(req, 'board/detail.html', context)

def delete(req, bpk):
    b = Board.objects.get(id=bpk)
    if req.user == b.writer:
        b.delete()
        return redirect('board:index')
    else:
        pass #메세지 넣을 곳
        return redirect('board:index')
    
def create(req):
    if req.method == "POST":
        s = req.POST.get("sub")
        c = req.POST.get("con")
        t = timezone.now()
        Board(subject=s, writer=req.user, content=c, pubdate=t).save()
        return redirect("board:index")
    return render(req, 'board/create.html')

def update(req, bpk):
    b = Board.objects.get(id=bpk)
    if b.writer == req.user:
        if req.method == "POST":
            s = req.POST.get("sub")
            c = req.POST.get("con")
            b.subject = s
            b.content = c
            b.save()
            return redirect("board:detail", bpk)
    else:
        pass # 경고메세지!
        return redirect('board:index')
    context = {
        "b": b
    }
    return render(req, 'board/update.html', context)

def likey(req, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.add(req.user)
    return redirect('board:detail',bpk)

def unlikey(req, bpk):
    b = Board.objects.get(id=bpk)
    b.likey.remove(req.user)
    return redirect('board:detail',bpk)

templates/board/create.html
{% extends 'base.html' %}

{% block con %}
    <br>
    <h1><b>게시글 작성 페이지</b></h1>
    <form method="post">
        {% csrf_token %}
        <input type="text" placeholder="제목을 입력하세요" name="sub"><br><br>
        <textarea cols="80" rows="8" placeholder="내용을 입력하세요" name="con"></textarea>
        <button>글 작성</button>
    </form>

{% endblock %}

templates/board/detail.html
{% extends 'base.html' %}

{% block con %}
    <br>
    <h1><b>{{ b.subject }}</b></h1>
    <br><hr>
    <img src="{{ b.writer.getpic }}" width="200px">
    <div>
        written by <b>{{b.writer}}</b>
    </div>
    <br><br>
    <textarea cols="80" rows="8" disabled>{{ b.content }}</textarea>
    <br><br>
    <a href="{% url 'board:index' %}"><button>목록</button></a>
    {% if b.writer == user %}
        <a href="{% url 'board:update' b.id %}"><button>수정</button></a>
        <a href="{% url 'board:delete' b.id %}"><button>삭제</button></a>
    {% endif %}


{% if user in b.likey.all %}
<a href="{% url 'board:unlikey' b.id%}"><button>좋아요 취소</button></a>
{% else %}
<a href="{% url 'board:likey' b.id %}"><button>좋아요❤</button></a>
{% endif %}
{% endblock %}

templates/board/index.html
{% extends 'base.html' %}

{% block con %}
{% load mathfilters %}

    <br><br>
    <h1>BOARD PAGE</h1>

    <br>
    <a href="{% url 'board:create' %}"><button>글 작성</button></a>
    <br>
    <table border="1">
        <tr>
            <th>NO</th>
            <th>SUBJECT</th>
            <th>SUMMARY</th>
            <th>WRITER</th>
            <th>LIKEY</th>
        </tr>
        {% if bset %}
            {% for i in bset %}
                <tr>
                    <td>{{ bset.start_index|add:forloop.counter0 }}</td>
                    <td><a href="{% url 'board:detail' i.id %}">{{ i.subject }}</a></td>
                    <td>{{ i.summary }}</td>
                    <td>{{ i.writer }}</td>
                    <th>{{ i.likey.count }}</th>
                </tr>
            {% endfor %}
        {% else %}
            {% if kw %}
                <tr>
                    <th colspan="5">검색 결과가 없습니다 🤦‍♂️ </th>
                </tr>
            {% else %}
                <tr>
                    <th colspan="5">첫번째 게시글을 작성해주세요 🤣</th>
                </tr>
            {% endif %}
        {% endif %}
    </table>
    <br><br>

    <!-- 이전 페이지 -->
    {% if bset.has_previous %}
        <a href="{% url 'board:index' %}?page=1&cate={{cate}}&kw={{kw}}"><button>홈</button></a>
        <a href="{% url 'board:index' %}?page={{ bset.previous_page_number }}&cate={{cate}}&kw={{kw}}"><button>이전</button></a>
    {% else %}
        <button disabled>홈</button>
        <button disabled>이전</button>
    {% endif %}

    <!-- 페이지 번호 -->
    {% for i in bset.paginator.page_range %}
        {% if i >= bset.number|sub:5 and bset.number|add:4 >= i %}
            <a href="{% url 'board:index' %}?page={{i}}&cate={{cate}}&kw={{kw}}"><button {% if bset.number == i %} disabled {% endif %}>{{i}}</button></a>
        {% endif %}
    {% endfor %}

    <!-- 다음 페이지 -->
    {% if bset.has_next %}
        <a href="{% url 'board:index' %}?page={{ bset.next_page_number }}&cate={{cate}}&kw={{kw}}"><button>다음</button></a>
        <a href="{% url 'board:index' %}?page={{ bset.paginator.num_pages }}&cate={{cate}}&kw={{kw}}"><button>마지막</button></a>
    {% else %}
        <button disabled>다음</button>
        <button disabled>마지막</button>
    {% endif %}
    
    <br><br>
    <form>
        <select name="cate">
            <option value="sub" {% if cate == "sub" %} selected {% endif %}>제목</option>
            <option value="wri" {% if cate == "wri" %} selected {% endif %}>작성자</option>
            <option value="con" {% if cate == "con" %} selected {% endif %}>내용</option>     
        </select>

        <input type="text" value="{{ kw }}" size="40" name="kw">

        <button>검색</button>
    </form>


{% endblock %}

templates/board/update.html
{% extends 'base.html' %}

{% block con %}
    <br>
    <h1><b>게시글 수정 페이지</b></h1>
    <form method="post">
        {% csrf_token %}
        <input type="text" value="{{ b.subject }}" name="sub"><br><br>
        <textarea cols="80" rows="8" name="con">{{ b.content }}</textarea>
        <button>글 수정</button>
    </form>

{% endblock %}